### ISSUE TITLE
BinExport is trowing an exception

### ISSUE THREAD

**Issue by Fenrisfulsur** [quarkslab/python-binexport#1] opened 2023-05-10 08:10 UTC
BinExport is trowing an exception (in `binexport/function.py`) when using the following code:
```
    p = qbindiff.Program(qbindiff.LoaderType.binexport, './firmware3v3.bin.BinExport')
    q = qbindiff.Program(qbindiff.LoaderType.binexport, './bootloader-apploader.axf.BinExport')
    differ = qbindiff.QBinDiff(p, q)
    differ.register_feature_extractor(qbindiff.features.BBlockNb, 1.0)
    matches = differ.compute_matching()
    ...
```
we get this error:
```
  File "binexport/function.py", line 174, in graph
    _ = self.blocks  # Load the CFG
  File "functools.py", line 981, in __get__
    val = self.func(instance)
  File "binexport/function.py", line 141, in blocks
    for bb_idx in self._pb_fun.basic_block_index:
AttributeError: 'NoneType' object has no attribute 'basic_block_index'
```
Which can be patched with the following (in `binexport/function.py`):
```
137  # Add a sanity check to prevent error, for yet unknown reason _pb_fun may be undefined
138  if self._pb_fun == None:
139    return bblocks
```

**Comment by patacca** [comment] 2023-11-10 17:17
Fixed in #8.
Feel free to open the issue again if the problem is still present.

**Closed by patacca** 2023-11-10 17:17 UTC
